### ISSUE TITLE
这个line是哪来的?主键?

### ISSUE THREAD

**Issue by justkuai** [drinkjava2/Multiple-Columns-Tree#1]
insert的时候, 怎么知道line, 别告诉我这是你自增主键啊, 那样就没法用了, 都是UUID当主键的

**Comment by drinkjava2** [comment]
id字段才是主键。 这个line字段不是主键，是由程序中对整个表或一棵树(如果按group分组)进行排序得来，如何排序见V3.0中的算法， 另外也可参考[https://github.com/drinkjava2/jSQLBox/blob/master/jsqlbox/src/test/java/test/examples/orm/TreeORMTest.java]( https://github.com/drinkjava2/jSQLBox/blob/master/jsqlbox/src/test/java/test/examples/orm/TreeORMTest.java)中的sortMySqlTree()方法。重排序是一个耗时的工作，仅当节点作复杂的移动操作时(例如移动子树到另一个节点），才考虑重排序。 
对于已经排好序的表，删除操作不需要重排序，这样虽然有跳号现象，但不影响使用。插入操作也不需要重排序，被插入的Node的行号为上个Node行号加1，并要将此Node以下的所有行号加1，虽然影响的行数非常多，但是理解和操作都很简单，例如要在line=9和line=10的两个节点之间插入一个新节点，则新节点行号应为10,原行号为10的将变为11, SQL操作为:
update tb2 set line=line+1 where line>=10;  //把10以后的行号加1
insert into tb (line,id,level) values (10,'T',4);  //执行插入新节点操作
以上两句SQL必须在一个事务中完成。

**Comment by drinkjava2** [comment]
补充一下，如行号本身就是跳号设计如按100000跳号，则新插入的节点的行号=(前一个行号+后一个行号)/2, 这样通常就不需要对其它行进行+1操作了。 仅当前后两个行号之间没有间隔，才需要对其它行进行调整。
