### ISSUE TITLE
哥们你这个优点, 是啥我没看出来啊

### ISSUE THREAD

**Issue by justkuai** [drinkjava2/Multiple-Columns-Tree#2]
我就直接 id, parentId, allParentId, level 这种结构就ok了啊

根据父查询所有子:   select * from t where allParentId like 'xx%';

移动节点, 直接一条 update 搞定
update t 
set parentId = <newParentId), 
allParentId = replace(allParentId, <老值>, <新值>
where id in
(select id from t where allParentId like 'xx%')

不知道你搞一堆能提升什么?

**Comment by drinkjava2** [comment]
你说的是Path Enumerations模式，对于少量的数据看不出来它的问题，但是树的深度很深时，例如达到1000层:
1)假设每个ID字段长度为10, 则最长的allParentID字符串长度为1000*10=10000个字节,这会严重占用磁盘空间，影响效率，如果深度更深或ID字段更长，则可能超出数据库支持的最大文本长度，而且其查询速度也会非常慢。
2)假设要将位于第100层的一个树节点移动到第500层的一个节点下，老值新值的替换或是重新生成也是一个耗时的长文本字符串替换工作，不如本文的整数加减计算快。 

对于数据量少的情况，用不着本文的方法,用最基本的Adjacency List模式配合数据库本身的递归查询(如果支持的话)，或是Path Enumerations模式都可以。仅对于海量数据和深度极深的树、且以查询速度为第一优先考虑的情况，才最适用于本文方法。另外本方法查询得到结果后，可以直接用在表格里，无须在内存中递归访问进行重排序。
