### ISSUE TITLE
Remove high level node also remove low level node

### ISSUE THREAD

**Issue by napoleon211092** [drinkjava2/Multiple-Columns-Tree#4]
Hi Mr/Ms drinkjava2
I have read your example. It's very helpful for me.
In my practices, I want to remove a higher node also remove its lower node.
For example:
Remove node "Database" means remove "MongoDB", "dbm" and "MongoTree".
Please help me.
Thank you in advance.

**Comment by drinkjava2** [comment]
Sorry just saw this issue.
For SQL delete a child tree is easy，for example: delete D and all child nodes:
delete from tb2 where  line>=7 and line< (select min(line) from tb2 where line>7 and level<=2)

I'm not familiar with mongoDb,  the demo is the first time I learned mongo, but delete tree should be similar like above logic, I'll think and give a real sample later.
Here I only give some FAKE codes, haven't debugged on real mango db:
```
var node = db.book.findOne( { _id: “Databases” } );
var next=db.book.findOne( { $and: [ {line: {$gt:node.line}}, {level:{$lte: node.level }}] } );
var collections=db.book.find( {$and: [{line: { $gt: node.line }}, {line: { $lt: next.line }}] } );
db.collection.deleteMany(collections);// this is fake code, not sure if it work
```

**Comment by drinkjava2** [comment]
Looks I have no time to give the real code for MangoDB,  just close this issue, the fake code is good enough to understand.
